### ISSUE TITLE
استفسار

### ISSUE THREAD

**Issue by moohaad** [khaledhosny/quran-typesetter#1]
السلام عليكم
هل هناك مشاكل في لاتك  لتقوم بعمل هذا السكربت
أم فقط للتجربة والاستكشاف

**Comment by khaledhosny** [comment]
لاتك لا یوفر المرونة التی أحتاجها. قد یمكن تطویع لواتك لیعطینی نفس النتائج، لكن أفضل بیثون على لوا.
